### ISSUE TITLE
meta-python2 still required?

### ISSUE THREAD

**Issue by kwavnet** [dev-0x7C6/meta-retro#38]
Hi,

first of all thank you for this awesome layer.
I was recently wondering, now that latest scarthgap is enabled, if meta-python2 really still is required?
So far I could only find a reference that remotely links to it with the mame cores.

So the question is: is meta-python2 really a hard requirement (also as there isn't any scarthgap support, and likely will never be, from the meta-python2 layer)?

**Comment by dev-0x7C6** [comment]
@kwavnet 

Hi, thanks, sorry for delay

I think that some mame cores used python2 stuff, but this might be no more required. I'll check that.
